DROP TABLE IF EXISTS DDL_TEST_DROP_TABLE;
/
DROP TABLE IF EXISTS DDL_TEST_CREATE_TABLE;
/
DROP TABLE IF EXISTS DDL_TEST_ALTER_TABLE;
/
DROP TABLE IF EXISTS DDL_TEST_PROC_TABLE;
/
DROP PROCEDURE IF EXISTS DDL_TEST_CREATE_PROC;
/
DROP PROCEDURE IF EXISTS DDL_TEST_ALTER_PROC;
/
DROP PROCEDURE IF EXISTS DDL_TEST_DROPPING_PROC;
/