CREATE TABLE TRX_TEST(ID INT, VAL VARCHAR(20));
/
CREATE TABLE TRX_TEST_AUTO_GEN_KEY(ID INT, VAL VARCHAR(20), AUTOGEN VARCHAR(20));
/
CREATE TABLE TRX_TEST_AUTO_GEN_KEY_SEQ(id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, val VARCHAR(20));
/
CREATE TRIGGER TG_TRX_TEST_AUTO_GEN_KEY_INSERT
ON TRX_TEST_AUTO_GEN_KEY
FOR INSERT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TRX_TEST_AUTO_GEN_KEY_SEQ (val) VALUES ('Val1');
    UPDATE TRX_TEST_AUTO_GEN_KEY SET AUTOGEN = CONCAT('id', SCOPE_IDENTITY());
END
/