CREATE TABLE IF NOT EXISTS SELECT_UPDATE_TEST_NUMERIC_TYPES(
  ID       INTEGER,
  SMALLINT_VAL SMALLINT,
  INT_VAL    INT,
  BIGINT_VAL   BIGINT,
  NUMERIC_VAL  NUMERIC,
  DECIMAL_VAL DECIMAL
);
/
CREATE TABLE IF NOT EXISTS SELECT_UPDATE_TEST_FLOAT_TYPES
(
    ID INT,
    REAL_VAL REAL,
    DOUBLE_VAL DOUBLE PRECISION
);
/
CREATE TABLE IF NOT EXISTS SELECT_UPDATE_TEST_STRING_TYPES
(
    ID INT,
    VARCHAR_VAL VARCHAR(20),
    TEXT_VAL TEXT
);
/
CREATE TABLE IF NOT EXISTS SELECT_UPDATE_TEST_COMPLEX_TYPES
(
    ID INT,
    BINARY_VAL BYTEA
);
/
CREATE TABLE IF NOT EXISTS SELECT_UPDATE_TEST_DATETIME_TYPES(
  ID         INTEGER,
  DATE_TYPE      DATE,
  TIME_TYPE      TIME,
  TIMEZ_TYPE     TIME,
  TIMESTAMP_TYPE  TIMESTAMP,
  TIMESTAMPZ_TYPE TIMESTAMPTZ
);
/
CREATE TABLE IF NOT EXISTS UPDATE_TEST_GENERATED_KEYS
(
    ID SERIAL NOT NULL,
    COL1  VARCHAR(20),
    COL2  INT,
    PRIMARY KEY (ID)
);
/
CREATE TABLE IF NOT EXISTS UPDATE_TEST_GENERATED_KEYS_NO_KEY
(
    COL1  VARCHAR(20),
    COL2  INT
);
