DROP TABLE IF EXISTS SELECT_UPDATE_TEST_NUMERIC_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_FLOAT_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_STRING_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_COMPLEX_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_DATETIME_TYPES;
/