DROP PROCEDURE CALL_TEST_IN_INTEGER_TYPES
/
DROP PROCEDURE CALL_TEST_OUT_INTEGER_TYPES
/
DROP PROCEDURE CALL_TEST_INOUT_INTEGER_TYPES
/
DROP PROCEDURE CALL_IN_FIXEDPOINT_TYPES
/
DROP PROCEDURE CALL_OUT_FIXEDPOINT_TYPES
/
DROP PROCEDURE CALL_INOUT_FIXEDPOINT_TYPES
/
DROP PROCEDURE CALL_IN_FLOAT_TYPES
/
DROP PROCEDURE CALL_OUT_FLOAT_TYPES
/
DROP PROCEDURE CALL_INOUT_FLOAT_TYPES
/
DROP PROCEDURE CALL_IN_STRING_TYPES
/
DROP PROCEDURE CALL_OUT_STRING_TYPES
/
DROP PROCEDURE CALL_INOUT_STRING_TYPES
/
DROP PROCEDURE CALL_IN_COMPLEX_TYPES
/
DROP PROCEDURE CALL_OUT_COMPLEX_TYPES
/
DROP PROCEDURE CALL_INOUT_COMPLEX_TYPES
/