DROP TABLE SELECT_UPDATE_INTEGER_TYPES
/
DROP TABLE SELECT_UPDATE_FIXEDPOINT_TYPES
/
DROP TABLE SELECT_UPDATE_FLOAT_TYPES
/
DROP TABLE SELECT_UPDATE_STRING_TYPES
/
DROP TABLE SELECT_UPDATE_COMPLEX_TYPES
/
DROP TABLE SELECT_UPDATE_DATETIME_TYPES
/
DROP TABLE UPDATE_GENERATED_KEYS
/
DROP SEQUENCE UPDATE_GENERATED_KEYS_SEQ
/