CREATE TABLE DDL_TEST_TABLE(X INTEGER, Y VARCHAR(20))
/
CREATE TABLE DDL_TEST_ALTER_TABLE (X INTEGER, Y VARCHAR(20), PRIMARY KEY (X))
/
CREATE INDEX DDL_TEST_DROP_INDEX ON DDL_TEST_TABLE (X)
/
CREATE TABLE DDL_TEST_DROP_TABLE(X INTEGER, Y VARCHAR(20))
/
CREATE PROCEDURE "DDL_TEST_DROPPING_PROC" (X IN NUMBER) IS
BEGIN
    dbms_output.put_line(X);
END;
/
