CREATE TABLE SELECT_UPDATE_INTEGER_TYPES(
  ID       INTEGER,
  INT_VAL    INTEGER
);
/
CREATE TABLE SELECT_UPDATE_FIXEDPOINT_TYPES(
  ID INTEGER,
  NUMERIC_VAL NUMERIC(9, 6),
  DECIMAL_VAL DECIMAL(12, 7)
);
/
CREATE TABLE SELECT_UPDATE_FLOAT_TYPES
(
    ID INT,
    FLOAT_VAL BINARY_FLOAT,
    DOUBLE_VAL BINARY_DOUBLE
);
/
CREATE TABLE SELECT_UPDATE_STRING_TYPES
(
    ID INT,
    CHAR_VAL CHAR(20),
    NCHAR_VAL NCHAR(20),
    VARCHAR_VAL VARCHAR2(20),
    NVARCHAR_VAL NVARCHAR2(20)
);
/
CREATE TABLE SELECT_UPDATE_COMPLEX_TYPES
(
    ID INT,
    BLOB_VAL BLOB,
    CLOB_VAL CLOB,
    NCLOB_VAL NCLOB
);
/
CREATE TABLE SELECT_UPDATE_DATETIME_TYPES(
  ID         INTEGER,
  DATE_VAL      DATE,
  TIMESTAMP_VAL     TIMESTAMP,
  TIMESTAMP_WITH_TZ_VAL  TIMESTAMP WITH TIME ZONE,
  TIMESTAMPZ_WITH_LOCAL_TZ_VAL TIMESTAMP WITH LOCAL TIME ZONE
);
/
CREATE TABLE UPDATE_GENERATED_KEYS
(
    ID NUMBER(10) NOT NULL,
    COL1  VARCHAR(20),
    CONSTRAINT auto_increment_tb_pk PRIMARY KEY (id)
);
/
CREATE SEQUENCE UPDATE_GENERATED_KEYS_SEQ;
/
CREATE OR REPLACE TRIGGER UPDATE_GENERATED_KEYS_INSERT
 BEFORE INSERT ON UPDATE_GENERATED_KEYS
 FOR EACH ROW
BEGIN
 SELECT UPDATE_GENERATED_KEYS_SEQ.nextval
 INTO :new.id
 FROM dual;
END;
/
