INSERT INTO SELECT_UPDATE_INTEGER_TYPES VALUES (1, 2147483647)
/
INSERT INTO SELECT_UPDATE_INTEGER_TYPES VALUES(2, NULL)
/
INSERT INTO SELECT_UPDATE_FIXEDPOINT_TYPES VALUES(1, 123.12, 123.12)
/
INSERT INTO SELECT_UPDATE_FIXEDPOINT_TYPES VALUES(2, NULL, NULL)
/
INSERT INTO SELECT_UPDATE_FLOAT_TYPES VALUES(1, 999.125698, 109999.123412378914545)
/
INSERT INTO SELECT_UPDATE_FLOAT_TYPES VALUES(2, NULL, NULL)
/
INSERT INTO SELECT_UPDATE_STRING_TYPES VALUES(1, 'Char column', 'යූනිකෝඩ් දත්ත', 'Varchar column', 'යූනිකෝඩ් දත්ත')
/
INSERT INTO SELECT_UPDATE_STRING_TYPES VALUES(2, NULL, NULL, NULL, NULL)
/
INSERT INTO SELECT_UPDATE_DATETIME_TYPES VALUES(2, NULL , NULL, NULL, NULL)
/
INSERT INTO SELECT_UPDATE_COMPLEX_TYPES VALUES(1, hextoraw('426c6f6220436f6c756d6e'), 'Clob Column', 'යූනිකෝඩ් දත්ත')
/
INSERT INTO SELECT_UPDATE_COMPLEX_TYPES VALUES(2, NULL, NULL, NULL)
/
INSERT INTO SELECT_UPDATE_DATETIME_TYPES VALUES(2, NULL, NULL, NULL, NULL)
