DROP TABLE IF EXISTS DDL_TEST_ALTER_TABLE;
/
DROP TABLE IF EXISTS DDL_TEST_TABLE;
/
DROP TABLE IF EXISTS DDL_TEST_DROP_TABLE;
/
DROP TABLE IF EXISTS DDL_TEST_CREATE_TABLE;
/
DROP PROCEDURE IF EXISTS DDL_TEST_DROPPING_PROC;
/