DROP TABLE IF EXISTS SELECT_UPDATE_TEST_INTEGER_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_FIXED_POINT_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_FLOAT_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_STRING_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_COMPLEX_TYPES;
/
DROP TABLE IF EXISTS SELECT_UPDATE_TEST_DATETIME_TYPES;
/
DROP TABLE IF EXISTS UPDATE_TEST_GENERATED_KEYS_NO_KEY;
/
DROP TABLE IF EXISTS UPDATE_TEST_GENERATED_KEYS;