DROP FUNCTION CALL_TEST_OUT_INTEGER_TYPES;
/
DROP FUNCTION CALL_TEST_INOUT_INTEGER_TYPES;
/
DROP FUNCTION CALL_TEST_INOUT_FIXED_POINT_TYPES;
/
DROP FUNCTION CALL_TEST_OUT_FIXED_POINT_TYPES;
/
DROP FUNCTION CALL_TEST_OUT_STRING_TYPES;
/
DROP FUNCTION CALL_TEST_INOUT_STRING_TYPES;
/
DROP FUNCTION CALL_TEST_INOUT_DATETIME_TYPES;
/
DROP FUNCTION CALL_TEST_OUT_COMPLEX_TYPES;
/
DROP FUNCTION CALL_TEST_INOUT_COMPLEX_TYPES;
/
DROP FUNCTION CALL_TEST_INOUT_FLOAT_TYPES;
/
DROP FUNCTION CALL_TEST_OUT_DATETIME_TYPES;
/
DROP FUNCTION CALL_TEST_OUT_FLOAT_TYPES;
/
