DROP TRIGGER TG_TRX_TEST_AUTO_GEN_KEY_INSERT ON TRX_TEST_AUTO_GEN_KEY;
/
DROP SEQUENCE UPDATE_GENERATED_KEYS_SEQ1;
/
DROP TABLE TRX_TEST_AUTO_GEN_KEY_SEQ;
/
DROP TABLE TRX_TEST_AUTO_GEN_KEY;
/
DROP TABLE TRX_TEST;
/
