CREATE TABLE TRX_TEST(ID INTEGER, VAL VARCHAR(20));
/
CREATE TABLE TRX_TEST_AUTO_GEN_KEY(ID INTEGER, VAL VARCHAR(20), AUTOGEN VARCHAR(20));
/
CREATE TABLE TRX_TEST_AUTO_GEN_KEY_SEQ(id SERIAL PRIMARY KEY);
/
CREATE SEQUENCE UPDATE_GENERATED_KEYS_SEQ1;
/
CREATE OR REPLACE FUNCTION tab1_number_inc()
   RETURNS "trigger" AS
    $BODY$
    BEGIN
      New.AUTOGEN:= CONCAT('id', nextval('UPDATE_GENERATED_KEYS_SEQ1'));
      Return NEW;
    END;
    $BODY$
    LANGUAGE 'plpgsql' VOLATILE;
/
CREATE TRIGGER TG_TRX_TEST_AUTO_GEN_KEY_INSERT
BEFORE INSERT ON TRX_TEST_AUTO_GEN_KEY FOR EACH ROW EXECUTE PROCEDURE tab1_number_inc();
/