DROP TABLE CALL_TEST_RETURN_VALUES;
/
DROP PROCEDURE CALL_TEST_OUT_NUMERIC_TYPES;
/
DROP PROCEDURE CALL_TEST_INOUT_NUMERIC_TYPES;
/
DROP PROCEDURE CALL_TEST_OUT_STRING_TYPES;
/
DROP PROCEDURE CALL_TEST_INOUT_STRING_TYPES;
/
DROP PROCEDURE CALL_TEST_INOUT_DATETIME_TYPES;
/
DROP PROCEDURE CALL_TEST_OUT_COMPLEX_TYPES;
/
DROP PROCEDURE CALL_TEST_INOUT_COMPLEX_TYPES;
/
DROP PROCEDURE CALL_TEST_INOUT_FLOAT_TYPES;
/
DROP PROCEDURE CALL_TEST_RETURN_RESULTSET;
/
DROP PROCEDURE CALL_TEST_OUT_DATETIME_TYPES;
/
DROP PROCEDURE CALL_TEST_OUT_FLOAT_TYPES;
/
